version: '2'
services:
    mark1-app:
        image: mark1
        external_links:
            - mark1-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mark1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mark1-mongodb:
        extends:
            file: mongodb.yml
            service: mark1-mongodb
