version: '2'
services:
    mark1-mongodb:
        container_name: mark1-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/mark1/mongodb/:/data/db/
